filter:
  branches:
    only:
      - master
      - develop
jobs:
  test:
    parameters:
      version: 15.5.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
          override-ci-command: yarn install
      - run: 
          command: yarn test
          name: Run YARN tests
orbs:
  node: 'circleci/node@4.0.1'
version: 2.1
workflows:
  tests:
    jobs:
      - test
